server:
  port: 9999 
spring:  
  application:  
    name: service-admin  
  mail:  
    host: smtp.163.com  
    username: idig8@163.com
    password: www.dig8.com
    properties:  
      mail.debug: false  
      mail.smtp.auth: true  
  boot:  
    admin:  
      notify:  
        mail:  
          to: idig8@qq.com
          from: idig8163.com
#          ignore-changes: UNKNOWN:UP  
      routes:  
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream 
               
