server:
  port: 8080
management:
  security:
    enabled: false  #关掉安全认证
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/limingios/springcloudconfig.git           # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码
    bus:
      trace:
        enabled: true     # 开启cloud bus的跟踪
  rabbitmq:
    host: 192.168.70.100
    port: 5672
    username: guest
    password: guest
    
    
    